# Build and push models package if models have changed
name: models

on:
  push:
    branches:
      - main
    paths:
      - 'models/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-models:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.models
          platforms: linux/amd64,linux/arm64
          push: true
          tags: models
          cache-from: type=registry,ref=${{env.REGISTRY}}/${{github.repository}}:buildcache-models
          cache-to: type=registry,ref=${{env.REGISTRY}}/${{github.repository}}:buildcache-models,mode=max
